version: "3.8"
# * =============================================== global networks and volumes =============================================== * #
networks:
  caddy:
  unami:
  changedetection:
  bookstack:


volumes: {}

services:
  # * =============================================== caddy =============================================== * #
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./env/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./config/caddy:/config
    networks:
      - caddy

  # * =============================================== unami =============================================== * #
  unami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:umami@unami-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: randomhashsalt
    depends_on:
      - unami-db
    restart: always
    networks:
      - caddy
      - unami

  unami-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./env/unami.schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./data/umami:/var/lib/postgresql/data
    restart: always
    networks:
      - unami

  # * =============================================== changedetection =============================================== * #
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./data/changedetection:/datastore
    environment:
      - BASE_URL=https://changedetection.ziyixi.science
      - USE_X_SETTINGS=1
      - FETCH_WORKERS=2
    restart: always
    networks:
      - caddy
      - changedetection

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:latest
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: always
    networks:
      - changedetection

  # * =============================================== frp =============================================== * #
  frp:
    # ref: https://calxu.github.io/note/20200301_vpn_2/
    image: snowdreamtech/frps:latest
    container_name: frp
    restart: always
    ports:
      - "12345:12345"
      - "7000:7000"
    volumes:
      - ./env/frps.ini:/etc/frp/frps.ini
      - ./data/frps.log:/log/frps.log

  # * =============================================== flame =============================================== * #
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - ./data/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./env/flame.env
    restart: always
    networks:
      - caddy

  # * =============================================== job-finder =============================================== * #
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - jobfinder
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  jobfinder:
    image: ghcr.io/ziyixi/job-finder:latest
    container_name: jobfinder
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.jobfinder.schedule: "@every 1h"
      ofelia.job-exec.jobfinder.no-overlap: 'true'
      ofelia.job-exec.jobfinder.command: "sh run_job.sh > log.txt"
    volumes:
      - ./data/job_finder/log.txt:/app/job_finder/log.txt
      - ./data/job_finder/job_finder.sqlite:/app/job_finder/job_finder.sqlite
    env_file: ./env/job_finder.env
    restart: always

  sqlite-web:
    image: ghcr.io/ziyixi/sqlite-web:latest
    container_name: sqlite-web
    depends_on:
      - jobfinder
    volumes:
      - ./data/job_finder:/data
    env_file: ./env/sqlite_web.env
    networks:
      - caddy
    restart: always

  # * =============================================== cloudmailin-todoist-app =============================================== * #
  cloudmailin-todoist-app:
    image: ghcr.io/ziyixi/cloudmailin-todoist-sync:latest
    container_name: cloudmailin-todoist-app
    restart: always
    env_file: ./env/cloudmailin.env
    networks:
      - caddy

  # * =============================================== bookstack =============================================== * #
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    volumes:
      - ./data/bookstack:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.ziyixi.science
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    depends_on:
      - bookstack_db
    networks:
      - bookstack
      - caddy
      
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstack
      - TZ=America/Detroit
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - ./data/bookstack_db:/config
    restart: unless-stopped
    networks:
      - bookstack

  # * =============================================== timetagger =============================================== * #
  timetagger:
    image: ghcr.io/almarklein/timetagger
    container_name: timetagger
    volumes:
      - ./data/timetagger:/root/_timetagger
    env_file: ./env/timetagger.env
    networks:
      - caddy


  # * =============================================== backup =============================================== * #
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ./env/backup.env
    volumes:
      - ./data:/backup/data:ro
      - ./config:/backup/config:ro
      - ./env:/backup/env:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro