version: "3.8"

services:
  # * =============================================== shadowsocks =============================================== * #
  shadowsocks:
    image: teddysun/shadowsocks-libev:latest
    container_name: shadowsocks
    ports:
      - "8388:8388"
    restart: always
    volumes:
      - ./env/config.json:/etc/shadowsocks-libev/config.json
